### ISSUE TITLE
Internal Server Error [2017-01-01 09:56:32,914] ERROR in app: Exception on /twitter/ [GET]

### ISSUE THREAD

**Issue by ab212** [bharadwaj6/gdt_search#1]
hi, need help.  I tried on run in local and it works with Duckduckgo, but it failed to search google and twitter. I got the following message: 
[2017-01-01 09:56:32,914] ERROR in app: Exception on /twitter/ [GET]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/email/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/anaconda2/envs/email/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/anaconda2/envs/email/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/anaconda2/envs/email/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/anaconda2/envs/email/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/Downloads/gdt_search/decorators.py", line 15, in decorated_function
    return view_fn()
  File "server.py", line 58, in search_twitter
    final_response['results'] = resp.json()['statuses']
KeyError: 'statuses'

any suggestion on how to fix this??? thank you

**Comment by bharadwaj6** [comment]
Hi @ab212 

Duckduckgo API is public and anyone can fetch that data, same is not the case with twitter and google. 
For Twitter, you have to create your own app and put the token in conf.py. 
For Google create a custom search engine on google and put the required params in conf. 

Both of those will start working once you have them in conf.

Cheers!
